const ProductData = [

    {
        id:1,
        product: "iPhone 16 Pro",
        price: 999.99,
        image: [
                "https://cdn.dxomark.com/wp-content/uploads/drafts/post-178568/Apple-iPhone-16-Pro-Max_featured-image-packshot-review-1024x691.png",
                "https://adminapi.applegadgetsbd.com/storage/media/large/iPhone-16-Pro-Max---16-Pro-Black-Titanium-2734.jpg",
                "https://imageio.forbes.com/specials-images/imageserve/66feb922afb1f2747d65b116/Apple-iPhone-16-finish-lineup-240909/960x0.jpg?format=jpg&width=960",
                "https://www.apple.com/v/iphone-16-pro/c/images/overview/product-stories/design/color__eaawe4bmivki_xlarge.jpg",
        ],
        stock: 12,
        color:[ "#1C1C1E", "#F5F5F7", '#D1CBC1', '#D4A373'  ],
        brand: "apple",
        category: "phone",
        featureItem: true,
        review: 4.1,
        description: `The iPhone 16 Pro and 16 Pro Max bring significant upgrades in design, camera functionality, and processing power. Both models feature a sleek titanium frame in colors like Desert Titanium and Black Titanium. The standout is the new 48MP Fusion camera with zero shutter lag, thanks to the A18 Pro chip and Apple Camera Interface, which ensures faster data transfer and power efficiency. The camera supports an impressive 4K 120 fps Dolby Vision video recording, providing cinema-quality footage with flexible playback speeds.

                        Apple's enhanced Camera Control adds DSLR-like precision, allowing users to slide their finger for zoom and depth adjustments. New Audio Mix features offer professional-grade audio adjustments, including Spatial Audio capture for immersive sound quality. Siri now boasts deeper contextual awareness, helping with on-device tasks without compromising privacy.`,
    },
    {
        id:2,
        product: "Nothing Phone 2a",
        price: 329,
        image: [
            "https://m.media-amazon.com/images/I/812emNTxp-L.jpg",
            "https://intl.nothing.tech/cdn/shop/files/Rectangle_496_f7457f8d-9bf2-4eea-8fbe-1aa9d2a9de7e_2160x.jpg?v=1709461449",
            "https://www.mobiledokan.co/wp-content/uploads/2024/07/Nothing-Phone-2a-Plus-Grey.webp",
            "https://static.alaneesqatar.qa/2024/03/Nothing-Phone-2a-8GB-256GB-Black-2_DrstDCZoJD.png",
        ],
        stock:23 ,
        color:["#1A1A1A","#F1F1F1"," #007BFF"],
        brand: "Nothing",
        category: "phone",
        featureItem: false ,
        review: 3.9,
        description: `The Nothing Phone (2a), released in March 2024, is a mid-range Android smartphone from the brand Nothing. It features a 6.7-inch AMOLED display with a 120Hz refresh rate and a peak brightness of 1300 nits, delivering vibrant visuals. The device runs on the MediaTek Dimensity 7200 Pro chipset and comes in multiple storage and RAM configurations: 128GB/8GB, 256GB/8GB, and 256GB/12GB options.

                    The phone is equipped with a 5000 mAh battery supporting 45W fast charging, which ensures long-lasting power. The rear camera setup includes dual 50MP sensors, offering standard and ultra-wide lenses, while the front camera is a 32MP sensor, ideal for selfies and video calls.

                    In terms of design, the phone features an IP54 rating, making it resistant to water and dust. Additionally, it includes the signature Glyph Interface, a series of LED lights on the back, which serve both functional and aesthetic purposes. The phone is available in several colors, including black, white, milk, and blue`,
    },
    {
        id:3,
        product: "Samsung Galaxy S24 Ultra",
        price: 789.99 ,
        image: [
            "https://www.jbhifi.com.au/cdn/shop/files/672257-Product-0-I-638490166202607153.jpg?v=1713419849",
            "https://adminapi.applegadgetsbd.com/storage/media/large/Galaxy-S24-Ultra-Titanium-Black-1587.jpg",
            "https://www.clove.co.uk/cdn/shop/files/GalaxyS24Ultra-TitaniumGrey_Back-Right_Pen_1200x.jpg?v=1705918644",
            "https://retail.com.pk/cdn/shop/files/FNL_Gallery_Ultra_800x600_Slide_Exclusive_Colors_1.webp?v=1706475223",
        ],
        stock: 7,
        color:["#D1B100","#6A4C8C","#5A5A5A","#121212"],
        brand: "Samsung",
        category: "phone",
        featureItem: false,
        review: 4.8,
        description: `The Samsung Galaxy S24 Ultra is equipped with a powerful 6.8-inch Dynamic AMOLED 2X display with a 120Hz refresh rate, offering excellent color accuracy and brightness. It boasts a Snapdragon 8 Gen 3 processor, paired with up to 16GB of RAM, ensuring smooth performance even for demanding tasks. The camera system is a standout, featuring a 200MP primary sensor, a 12MP ultrawide camera, and two telephoto sensors (10MP each). The phone also offers up to 1TB of storage and includes a 5000mAh battery that supports 45W fast charging. It runs on One UI based on Android 14`,
    },
    {
        id:4,
        product: "Xiaomi 14 Ultra",
        price: 1085,
        image: [
            "https://www.gsmarenabd.net/wp-content/uploads/2024/07/Xiaomi-14-Ultra.jpg",
            "https://www-mobiledokan.co/wp-content/uploads/2024/06/Xiaomi-14-Ultra-600x600.webp",
            "https://adminapi.applegadgetsbd.com/storage/media/large/Xiaomi-14-Ultra-Blue-2877.jpg",
            "https://www.notebookcheck-cn.com/uploads/tx_nbc2/Xiaomi_14_Ultra.jpg",
        ],
        stock: 5,
        color:[" #1C1C1C","#F5F5F5"],
        brand: "Xiaomi",
        category: "phone",
        featureItem: true,
        review: 4.6,
        description: `Xiaomi 14 Ultra is a premium flagship smartphone designed for professional photography enthusiasts and power users. It boasts a 6.74-inch AMOLED display with a 3200 x 1440p resolution and a 120Hz refresh rate, offering HDR10+ and a peak brightness of 3000 nits. Under the hood, it runs on the Snapdragon 8 Gen 3 chipset, coupled with up to 16GB of RAM and a maximum of 1TB storage, though global variants will be capped at 512GB. The phone is equipped with a robust 5300mAh battery, supporting 90W wired charging and 50W wireless charging. On the camera front, it features a Leica quad-camera system with a 50MP primary sensor, ultra-wide, and telephoto lenses, offering versatile focal lengths from 12mm to 240mm​`,
    },
    {
        id:5,
        product: "Huawei Mate XT Ultimate",
        price: 2800,
        image: [
            "https://www.techspecs.info/_next/image/?url=https%3A%2F%2Fwww.techspecs.info%2Fuploads%2FHuawei_Mate_XT_specification_801ec64898.jpg&w=640&q=75",
            "https://www.giztop.com/media/catalog/product/cache/dc206057cdd42d7e34b9d36e347785ca/x/t/xt-black.jpg",
            "https://www.ectgadget.com/assets/images/products/gallery/527947_huawei-mate-xt-ultimate-44.jpg",
            "https://phoneaqua.com/assets/images/products/Huawei%20Mate%20XT.jpg",
        ],
        stock: 3,
        color:["#D32F2F", "#000000"],
        brand: "huawei",
        category: "phone",
        featureItem: true ,
        review: 5,
        description: `The Huawei Mate XT Ultimate is available in two color options: Red and Black. It features a 10.2-inch tri-foldable LTPO OLED display with a high resolution of 2232 x 3184 pixels and a 120Hz refresh rate for smooth visuals. Powered by the Kirin 9010 chipset, the phone comes with 16GB of RAM and offers storage options of 256GB, 512GB, or 1TB. The rear camera setup includes a 50 MP main sensor, a 12 MP ultrawide lens, and a 12 MP periscope lens with 5.5x optical zoom, while the front camera is 8 MP. It houses a 5600 mAh battery with 66W fast charging, 50W wireless charging, and 7.5W reverse wireless charging capabilities. The Huawei Mate XT Ultimate runs on HarmonyOS 4.2, supports 5G connectivity, and includes a side-mounted fingerprint scanner, stereo speakers, and various sensors.`,
    },
    {
        id:6,
        product: "Realme GT 7 Pro",
        price: 600,
        image: [
            "https://www.mobiledokan.co/wp-content/uploads/2024/08/Realme-GT7-Pro-Orange.webp",
            "https://www.gizchina.com/wp-content/uploads/images/2024/08/imagem_2024-08-06_020243610.png",
            "https://myfusionmobile.com/wp-content/uploads/2024/09/Realme-GT7-Pro-500x500.png",
            "https://fdn.gsmarena.com/imgroot/news/24/06/realme-gt7-pro-leak/inline/-1200/gsmarena_001.jpg"
        ],
        stock: 2,
        color:["#FF6347","#A9A9A9","#FFFFFF"],
        brand: "Realme",
        category: "phone",
        featureItem: false,
        review: 4,
        description: `The Realme GT 7 Pro, launched in November 2024, is a premium flagship phone with a 6.78-inch LTPO OLED display offering a smooth 120Hz refresh rate, HDR10+, and Dolby Vision support. Powered by the Snapdragon 8 Gen Elite chipset, it features up to 16GB of RAM and up to 1TB of storage. The device boasts a versatile triple-camera setup, including a 50 MP primary sensor, a 50 MP telephoto lens with 3x optical zoom, and an 8 MP ultrawide lens. The front camera is 16 MP, perfect for 1080p video recording. With a massive 6,500mAh battery, it supports 120W fast charging.`,
    },
    {
        id:7,
        product: "OnePlus 12",
        price: 709.95,
        image: [
            "https://image01.oneplus.net/media/202405/28/b96848b7acd10dafde32203d12f6fea7.png?x-amz-process=image/format,webp/quality,Q_80",
            "https://www.gizmochina.com/wp-content/uploads/2023/07/OnePlus-12-1-500x500.jpg",
            "https://www.oneplus.com/content/dam/oasis/page/waffle/images-design-part4-img3-1-100.jpg.webp",
            "https://kryinternational.com/wp-content/uploads/2024/03/OnePlus-12.jpg"
        ],
        stock: 5,
        color:["#1D1F21","#F9F9F9"],
        brand: "OnePlus",
        category: "phone",
        featureItem: false,
        review: 4.5,
        description: `The OnePlus 12 is available in several color variants including Black, White, and a limited-edition color that might change depending on the region or special edition releases. Its design emphasizes a premium feel with a lightweight frame and a high-quality glass back.

                    In terms of specifications, the OnePlus 12 is expected to be powered by a Qualcomm Snapdragon 8 Gen 3 processor, offering high performance and efficiency for gaming and multitasking. The phone comes with 12GB, 16GB, or even 24GB of LPDDR5X RAM, and the storage options go up to 1TB with UFS 4.0 for fast read/write speeds. The display is a 6.7-inch AMOLED screen with a 120Hz refresh rate and supports HDR10+ for vibrant colors. The rear camera setup includes a 50MP primary sensor, a 64MP telephoto lens with 3x optical zoom, and a 48MP ultrawide lens, allowing for versatile photography capabilities including 8K video recording at 24fps. The front camera is a 32MP sensor capable of 4K video recording.

                    The battery capacity is 5400mAh, with 100W fast charging that charges the phone to 70% in just 15 minutes and 50W wireless charging. It supports 5G connectivity and offers a host of features including Wi-Fi 7, Bluetooth 5.4, and Dolby Atmos for immersive sound. The phone runs on OxygenOS based on Android 14. For security, it includes an in-display fingerprint sensor, and it also supports eSIM functionality.`,
    },
    {
        id:8,
        product: "Oppo Find X8",
        price: 745.05 ,
        image: [
            "https://www.mobiledokan.co/wp-content/uploads/2024/02/Oppo-Find-X8-Blue.webp",
            "https://www.gizmochina.com/wp-content/uploads/2024/08/Oppo-Find-X8-series-render-722x1024.jpg",
            "https://i.gadgets360cdn.com/products/large/oppo-find-x8-680x800-1729779603.jpg",
            "https://www.vopmart.com/media/catalog/product/cache/ee14c5ab36c97d39d331f867fa3bee63/o/p/oppo_find_x8.jpg"
        ],
        stock: 8,
        color:["#000000","#FFFFFF","#1E90FF","#FF1493"],
        brand: "Oppo",
        category: "phone",
        featureItem: false,
        review: 3.5,
        description: `The Oppo Find X8 offers a sleek design with a 6.6-inch AMOLED display that supports a 120Hz refresh rate and a peak brightness of 4500 nits. Powered by the MediaTek Dimensity 9400 chipset and paired with 12GB of RAM and 256GB of internal storage, it ensures excellent performance for demanding tasks and multitasking. The phone is equipped with a triple-camera system, including a 50MP main camera, 50MP telephoto camera with 3x optical zoom, and a 50MP ultra-wide camera, alongside a 32MP front camera for high-quality selfies. The device is water and dust resistant with an IP69 rating and offers fast charging capabilities, supporting up to 80W wired charging and 50W wireless charging. The 5630 mAh battery ensures long-lasting use throughout the day. The Oppo Find X8 runs on Android 15 with ColorOS 15, featuring advanced AI and design features. Available in four colors—Black, White, Blue, and Pink—the phone combines functionality with style`,
    },
    {
        id:9,
        product: "pixel 9 pro",
        price: 999,
        image: [
            "https://adminapi.applegadgetsbd.com/storage/media/large/Pixel-9-Pro-Obsidian-6557.jpg",
            "https://www.shopz.com.bd/wp-content/uploads/2024/08/Google-Pixel-9-Pro-XL-4.jpg",
            "https://mobilebuzzbd.com/wp-content/uploads/2024/08/Google-Pixel-9-Pro.jpg",
            "https://www.notebookcheck.net/fileadmin/Notebooks/News/_nc4/pixel-9-pro-deals-pixel-9.jpg",
        ],
        stock: 30,
        color:["#000000","#FFFFFF","#FF5733"],
        brand: "google",
        category: "phone",
        featureItem: true,
        review: 4.5,
        description: `The Google Pixel 9 Pro is available in three color variants: "Just Black," "Clearly White," and "Oh So Orange." This flagship smartphone is equipped with a 6.7-inch OLED display, offering a resolution of 3200 x 1440 pixels for sharp and vibrant visuals. It is powered by the Google Tensor chip, which enhances the overall performance, especially in AI-related tasks. The Pixel 9 Pro features a triple-camera system with a 50MP primary sensor, a 12MP ultrawide lens, and a 48MP telephoto lens, providing versatile photography options. The device also includes an impressive 12GB of RAM, ensuring smooth multitasking, and storage options of up to 512GB. It runs on the latest Android OS with custom Google features, offering a seamless user experience, and includes a large battery that supports fast charging and wireless charging. Additionally, the phone is 5G capable, making it future-proof for high-speed internet connections.`,
    },
    {
        id:10,
        product: "vivo X200 Pro",
        price:  828.86,
        image: [
            "https://www.mobileana.com/wp-content/uploads/2024/10/vivo-X200-Pro-mini-Green.webp",
            "https://cdn.droidchart.com/p/92/9222/vivo-x200-pro-v2405a-6.webp",
            "https://www.mobiledokan.co/wp-content/uploads/2024/08/Vivo-X200-Pro-Blue.webp",
            "https://hi-tech.ua/wp-content/uploads/2024/10/vivo-x200-x200-pro-1.jpg",
        ],
        stock: 9,
        color:["#1C3D60","#000000","#FFFFFF","#B1B6B8"],
        brand: "vivo",
        category: "phone",
        featureItem: false ,
        review: 4,
        description: `In terms of its specifications, the Vivo X200 Pro boasts a sleek design with a 6.78-inch AMOLED display offering a 120Hz refresh rate, providing smooth visuals. It's powered by the MediaTek Dimensity 9400 processor and comes with up to 16GB of RAM and 512GB of internal storage. The phone features a triple-camera setup, including a 50 MP main camera, a 200 MP periscope telephoto camera with 3.7x optical zoom, and a 50 MP ultrawide camera, capable of recording 8K videos. The front camera is a 32 MP unit designed for high-quality selfies and 4K video recording. It also includes a large 6000 mAh battery with fast charging capabilities (90W wired and 30W wireless) and has IP69 water and dust resistance. The device runs Android 15 and offers premium features like stereo speakers, NFC, and a fingerprint sensor under the display`,
    },
    {
        id:11,
        product: "Nothing Watch Pro 2",
        price: 80,
        image: [
            "https://adminapi.applegadgetsbd.com/storage/media/large/CMF-by-Nothing-Watch-Pro-2-BT-calling-Smart-Watch-Dark-Gray-1622.jpg",
            "https://www.gadstyle.com/wp-content/uploads/2024/07/cmf-by-nothing-watch-pro-2-60hz-amoled-display-watch-4.webp",
            "https://gadgetnmusic.com/wp-content/uploads/2024/07/Cmf-By-Nothing-Watch-Pro-2-60hz-Amoled-Display-Watch-1.webp",
            "https://diamu.com.bd/wp-content/uploads/2024/07/CMF-by-Nothing-Watch-Pro-2-4.jpg",
        ],
        stock: 90,
        color:["#4B4B4B","#B2BEB5","#FF7F00","#1E90FF"],
        brand: "Nothing",
        category: "watch",
        featureItem: true,
        review: 4.5,
        description: `The Nothing Watch Pro 2 is a stylish and affordable smartwatch featuring a 1.32-inch AMOLED display with a high resolution of 466 x 466 pixels and brightness reaching 620 nits, ensuring visibility even in bright settings. It supports Bluetooth calling, GPS, and multiple fitness-tracking options. With over 100 customizable watch faces and a battery life extending up to 13 days, it's designed for both functionality and personalization. The watch is available in Dark Gray and Ash Gray with silicone bands and in Orange and Blue with vegan leather straps.`,
    },
    {
        id:12,
        product: "Apple Watch Ultra 2",
        price: 800,
        image: [
            "https://adminapi.applegadgetsbd.com/storage/media/large/Alpine-Loop-Blue-3303.png",
            "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/MYPD3ref_VW_34FR+watch-case-49-titanium-black-ultra2_VW_34FR+watch-face-49-ocean-ultra2_VW_34FR?wid=752&hei=720&bgc=fafafa&trim=1&fmt=p-jpg&qlt=80&.v=VEREVGFsQzRDQXZXemdUckh4dmo3M2pDV2hhem5qNnpDenFtKzI1OXdzWjRaeVR4RW9XWXhWVHRHeXZEa3AwcGZsNDErT2hQbWVmS0VCWlVweVY1UHBiVmVXUVJPYnV1S0FZc3FMLzd3SDd1WDdBMEYxOHdORVUzNUYwZW1oWG1RNjMyWnVvUG5OaUp1YWFFeUM2QmI2c0dDUGtHRjJ4SWtBTUxrSTdwRTI3bTUyQ1MxU1UvNlByY3lHWllzVjF5T3hGaHhOWmQ0TEdFQ1pIWVhrdU1oUFV1U0dtR29TZGVEaVVPVzB0LzM5OA",
            "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/49-cell-titanium-black-milanese-loop-black-ultra_GEO_IN?wid=1200&hei=630&fmt=jpeg&qlt=95&.v=1725035567280",
            "https://www.custommacbd.com/cdn/shop/files/watch-ultra2-49-mm-ocean-orange-Custom-Mac-BD.jpg?v=1696142082",
        ],
        stock: 45,
        color:["#D4D4D4"],
        brand: "apple",
        category: "watch",
        featureItem: true,
        review: 5,
        description: `The Apple Watch Ultra 2 is available in a single premium color option: Titanium. This rugged, high-performance smartwatch is crafted to handle extreme conditions, featuring a 49mm titanium case that's lightweight, durable, and corrosion-resistant. It boasts an Always-On Retina display with up to 3000 nits brightness, making it highly visible even in direct sunlight. Designed for outdoor enthusiasts and athletes, it includes advanced GPS and dual-frequency technology for improved tracking accuracy in remote areas. With up to 36 hours of battery life on a single charge, or up to 72 hours in low-power mode, it ensures extended use during adventures. It offers comprehensive health and fitness tracking, including heart rate monitoring, blood oxygen measurements, ECG, sleep stages tracking, and an Action Button for quick access to customized functions. Water-resistant to 100 meters, the Ultra 2 is optimized for both oceanic and mountain explorations. It also supports customizable watch faces and is compatible with a range of specialized bands tailored for various activities.`,
    },
    {
        id:13,
        product: "Galaxy Watch 7",
        price: 200,
        image: [
            "https://gadgetnmusic.com/wp-content/uploads/2024/08/Samaung-Galaxy-Watch-7-AI-Smart-Watch-1.png",
            "https://d61s2hjse0ytn.cloudfront.net/color/1246/Post_Template_33.webp",
            "https://compughana.com/media/catalog/product/cache/9d08971813a040f8f96067a40f75c615/s/a/samsung_fe.jpg",
            "https://compughana.com/media/catalog/product/cache/9d08971813a040f8f96067a40f75c615/s/a/samsung_earbud_14.jpg",
        ],
        stock: 15,
        color:["#556B2F", "#C0C0C0", "#F5F5DC"],
        brand: "samsung",
        category: "watch",
        featureItem: true,
        review: 4,
        description: `The Samsung Galaxy Watch 7, featuring a sleek design with a 3nm processor, enhances daily health monitoring through its advanced BioActive Sensor, which accurately tracks heart rate, sleep, and fitness metrics. Equipped with Galaxy AI, this watch offers personalized health insights and an Energy Score feature that helps you optimize daily routines. With Dual-Frequency GPS for precise outdoor navigation, it's ideal for active users. Available in two sizes (40mm and 44mm), the Galaxy Watch 7 is offered in three elegant colors: Green, Silver, and Cream. Each color option complements the watch's premium aesthetic, designed to blend style with functionality.`,
    },
    {
        id:14,
        product: "G-SHOCK",
        price: 85,
        image: [
            "https://www.watchia.com/media/catalog/product/cache/4c7956d99fb9002e2009e651899a50c2/g/a/ga-110gb-1aer.jpg",
            "https://www.watchia.com/media/catalog/product/cache/4c7956d99fb9002e2009e651899a50c2/g/a/ga-100-1a1er.jpg",
            "https://www.watchia.com/media/catalog/product/cache/074b491b7c680a360b2429f2a25e33dc/g/a/ga-2100-1a1er_1_.jpg",
            "https://www.bestpricedwatches.com/cdn/shop/products/GA110HC-1A_xlarge_1600x.png?v=1483473099",
        ],
        stock: 23,
        color:["#000000", "#FFFFFF", "#FF0000", "#0033CC", "#006400", "#FF8C00", "#FFFF00", "#808080"],
        brand: "casio",
        category: "watch",
        featureItem: false,
        review: 5,
        description: `G-SHOCK watches are renowned for their durability, ruggedness, and functionality, appealing to both adventure enthusiasts and those seeking a stylish yet resilient timepiece. These watches typically come in a wide range of colors, from classic black and white to bold options like blue, red, green, and even camouflage patterns. Each model offers various features tailored to outdoor and urban lifestyles, including shock resistance, water resistance up to 200 meters, and features like stopwatch, countdown timer, alarms, and sometimes additional technology such as solar power or Bluetooth connectivity. The combination of high-quality resin construction and innovative design makes G-SHOCKs both comfortable and dependable for daily wear and extreme activities alike, providing versatile style choices along with impressive functionality.`,
    },
    {
        id:15,
        product: "Xiaomi Watch 2",
        price: 150,
        image: [
            "https://m.media-amazon.com/images/I/61ylCKZlALL.jpg",
            "https://i02.appmifile.com/651_operatorx_operatorx_opx/30/11/2023/d9a896d3b8819d3b5e979745ceae8e48.png",
            "https://adminapi.applegadgetsbd.com/storage/media/large/Xiaomi-Watch-2-SIlver-5181.jpg",
            "https://cdn.webshopapp.com/shops/346435/files/449536305/1000x1000x2/bandz-bandz-xiaomi-watch-2-pro-titanium-strap-clas.jpg",
        ],
        stock: 9,
        color:["#2F4F4F", "#F5F5F5", "#000000"],
        brand: "Xiaomi",
        category: "watch",
        featureItem: false,
        review: 3,
        description: `The Xiaomi Watch 2 comes in three colors: Pine Green, White Leather, and Recycled Black. This smartwatch features a 1.43-inch AMOLED display with a 466x466 resolution, achieving vibrant clarity with up to 600 nits of brightness. The aluminum alloy body is lightweight, enhancing comfort for extended wear. It is powered by the Snapdragon W5+ Gen 1 processor, has 2GB of RAM, and 32GB of storage, ensuring smooth performance for fitness tracking and app usage. With a battery life lasting up to 65 hours, this watch supports magnetic charging and can be fully charged in about 45 minutes. It includes 5ATM water resistance, dual-band GPS, and various sensors for health monitoring, such as a heart rate sensor and gyroscope. The watch is compatible with Android 8.0 and above, integrating seamlessly with the Mi Fitness app.`,
    },
    {
        id:16,
        product: "Pixel Watch 2",
        price: 320,
        image: [
            "https://adminapi.applegadgetsbd.com/storage/media/large/Pixel-Watch-2-Matte-Black-3576.jpg",
            "https://diamu.com.bd/wp-content/uploads/2023/10/Google-Pixel-Watch-2-Bay-Polished-Silver-Aluminum-300x300.jpg",
            "https://www.mobilebazar.com.bd/assets/img/Google-Pixel-Watch-2.webp",
            "https://shopcgx.com/cdn/shop/files/6559649_rd.jpg?v=1709355692",
        ],
        stock: 3,
        color:["#000000", "#C0C0C0", "#FFD700"],
        brand: "google",
        category: "watch",
        featureItem: false,
        review: 4.5,
        description: `The Google Pixel Watch 2 is a sleek and compact smartwatch featuring a 1.2-inch AMOLED display with Gorilla Glass 5 for scratch resistance and 1,000 nits of brightness, ensuring clear visibility even in bright conditions. With a 41mm case and a weight of 31 grams without the strap, it's both lightweight and comfortable. This model has significant health and fitness enhancements, including multi-LED heart rate sensors, a skin temperature sensor, and Fitbit's advanced health tracking, such as continuous electrodermal activity (cEDA) for stress monitoring, and ECG capabilities. Running on Wear OS 4, it utilizes the Snapdragon W5 chipset for smooth performance and better efficiency. The Pixel Watch 2 also includes built-in GPS, Bluetooth 5.0, and optional LTE connectivity, supporting seamless notifications and connectivity on the go. Battery life reaches up to 24 hours with the always-on display enabled, and it charges to 80% in about 43 minutes, prioritizing faster charging and battery efficiency. It's available in three colors: Matte Black, Polished Silver, and Champagne Gold.`,
    },
    {
        id:17,
        product: "OnePlus Watch 2",
        price: 250.45,
        image: [
            "https://extremegadgets.com.bd/wp-content/uploads/2024/09/OnePlus-Watch-2-Wear-OS-Hybrid-Watch-3.jpg",
            "https://gadgetnmusic.com/wp-content/uploads/2024/03/Oneplus-Watch-2-Wear-OS-By-Google-2-1.jpg",
            "https://extremegadgets.com.bd/wp-content/uploads/2024/09/main-image-5-16.jpeg",
            "https://www.mytrendyphone.eu/images/OnePlus-Watch-2-5491100053-5ATM-IP68-Black-Steel-6921815626626-19062024-00-p.webp"
        ],
        stock: 9,
        color:["#1A1A1A", "#C0C0C0"],
        brand: "OnePlus",
        category: "watch",
        featureItem: false,
        review: 3.5,
        description: `The OnePlus Watch 2 is available in two colors: Midnight Black and Classic Silver. It features a 1.43-inch AMOLED display with a high resolution of 466x466 pixels and a peak brightness of 600 nits, providing vivid visuals under various lighting conditions. Powered by the Snapdragon W5 Gen 1 chipset with 2GB RAM and 32GB of internal storage, the watch runs on Wear OS 4 with additional real-time OS support, allowing a fluid experience and support for third-party apps. For fitness enthusiasts, it includes over 100 sports modes and automatic detection for activities like walking, running, and cycling. It also provides extensive wellness monitoring, including heart rate, SpO2, and sleep tracking. The 500mAh battery supports up to 100 hours of usage in Smart Mode, and it can be fully charged in 60 minutes, with a 10-minute charge offering a full day's power. The OnePlus Watch 2 supports Bluetooth 5.0, dual-band Wi-Fi, and GPS tracking with multiple positioning systems for accurate outdoor exercise data.`,
    },
    {
        id:18,
        product: "AirPods Pro 2",
        price: 250,
        image: [
            "https://www.shopz.com.bd/wp-content/uploads/2022/09/Apple-AirPods-Pro-2nd-Generation-Wireless-Earbuds-with-MagSafe-Charging-Case-1.jpg",
            "https://www.apple.com/newsroom/images/2023/09/apple-introduces-new-airpods-pro-2nd-generation/tile/Apple-AirPods-Pro-2nd-generation-USB-C-connection-230912.jpg.news_app_ed.jpg",
            "https://cdn0.it4profit.com/s3size/rt:fill/w:900/h:900/g:no/el:1/f:webp/plain/s3://cms/product/b7/66/b76600849c984e6d6b449ba196c534d0/230918065429164455.webp",
            "https://www.spigen.com.bd/image/cache/catalog/Air%20Pods%20Pro%202/Urban%20Fit/Urban-Fit-Case--Airpods-Pro-2-910x1155.jpg"
        ],
        stock: 53,
        color:["#FFFFFF"],
        brand: "apple",
        category: "earphone",
        featureItem: true,
        review: 5,
        description: `The AirPods Pro 2 are typically available in a single standard color, which is white. This premium earphone model is designed for a top-tier audio experience, offering improved noise cancellation, adaptive transparency, and enhanced audio drivers for richer sound quality across frequencies. The second-generation AirPods Pro also include advanced features like Personalized Spatial Audio for immersive sound tailored to the user's ear shape, touch controls for volume and playback, and a longer battery life that provides up to 6 hours of listening time per charge and up to 30 hours with the case. The case is equipped with a U1 chip for Precision Finding and a built-in speaker, making it easier to locate and offering MagSafe compatibility for convenient charging. With an IPX4 water and sweat resistance rating, the AirPods Pro 2 are suited for active lifestyles and daily use, providing comfort and a secure fit through customizable silicone ear tips in multiple sizes.`,
    },
    {
        id:19,
        product: "Nothing Ear 2",
        price: 120,
        image: [
            "https://adminapi.applegadgetsbd.com/storage/media/large/NOTHING-Ear-(4)-5414.jpg",
            "https://images-cdn.ubuy.co.in/64bd14c8f06afd11cc05e495-nothing-ear-2-wireless-earbuds-active.jpg",
            "https://adminapi.applegadgetsbd.com/storage/media/large/CMF-by-Nothing-Buds-Pro-2-Hybrid-ANC-Wireless-Earbuds-Dark-Grey-7679.jpg",
            "https://munkong.sgp1.cdn.digitaloceanspaces.com/munkong-production/2024-03-16/1714462413774.jpg"
        ],
        stock: 11,
        color:["#FFFFFF", "#000000"],
        brand: "Nothing",
        category: "earphone",
        featureItem: true,
        review: 4,
        description: `The Nothing Ear (2) is a high-performance pair of wireless earbuds designed to deliver a balanced sound with rich mids and controlled highs, enhancing audio detail without sounding harsh. The earbuds feature an 11.6mm driver with a graphene diaphragm for precise sound, supported by advanced equalizer settings via the Nothing X app, which lets users customize the audio experience. Equipped with active noise cancellation (ANC) that can reduce up to 40 dB of ambient noise, the earbuds also offer adaptive transparency mode for environmental awareness. The battery life reaches up to 36 hours with the case, and just 10 minutes of charging yields 8 hours of playback. Made for durability, the buds are rated IP54 for dust and water resistance, while the charging case is IP55. The design remains sleek, with Nothing's signature transparent look, and offers only one color—white with a transparent casing.`,
    },
    {
        id:20,
        product: "Realme Buds Air 2",
        price: 40,
        image: [
            "https://vibegaming.com.bd/wp-content/uploads/2021/10/0016201_realme-buds-air-2-active-noise-cancellation-25hrs-total-playback-88ms-super-low-latency-original-rea.png",
            "https://www.shopz.com.bd/wp-content/uploads/2021/06/Realme-Buds-Air-2-White.jpg",
            "https://adminapi.applegadgetsbd.com/storage/media/large/realme-Buds-Air-2-Green-4266.jpg",
            "https://m.media-amazon.com/images/I/71WdDANbqDL._AC_UF1000,1000_QL80_.jpg",
        ],
        stock: 0,
        color:["#FFFFFF", "#1A1A1A"],
        brand: "Realme",
        category: "earphone",
        featureItem: false,
        review: 2.5,
        description: `The Realme Buds Air 2 are available in two distinct color options: Closer White and Closer Black. These earbuds are designed to deliver high-quality audio with advanced features like Active Noise Cancellation (ANC), reducing ambient noise by up to 25 dB, and a dual-mic noise cancellation for calls. Equipped with a 10mm Hi-Fi Bass Boost Driver and a custom R2 chip, they offer an enhanced listening experience with a stable connection and efficient power consumption. The buds support Bluetooth 5.2, enabling low latency (88ms) for gaming and providing up to 25 hours of playback on a single charge with ANC off (22.5 hours with ANC on). The Buds Air 2 also feature an IPX5 water resistance rating, which means they can withstand splashes and sweat, making them suitable for workouts. The charging case is compact and supports fast charging, giving users 2 hours of playback with just 10 minutes of charging, while a full charge takes around 2 hours.`,
    },
    {
        id:21,
        product: "Google Pixel Buds Pro",
        price: 190,
        image: [
            "https://uniquegadget.com.bd/wp-content/uploads/2022/10/Google-Pixel-Buds-Pro-1.jpg",
            "https://buymobile.co.nz/cdn/shop/products/GOG-PIXEL-BUDS-PRO-LEMfront_2048x2048.jpg?v=1666701393",
            "https://diamu.com.bd/wp-content/uploads/2022/10/Google-Pixel-Buds-Pro-3-1.jpg",
            "https://s3.us-east-1.amazonaws.com/product-image-bucket-prod-us/597900-Product-1-I-637958093577575835.jpg"
        ],
        stock: 5,
        color:["#282828", "#E9E7DA", "#DADDE1", "#FB806F"],
        brand: "google",
        category: "earphone",
        featureItem: false,
        review: 5,
        description: `The Google Pixel Buds Pro typically come in four stylish colors: Charcoal, Lemongrass, Fog, and Coral. These earbuds feature Active Noise Cancellation with Silent Seal, adapting to your ear shape for a personalized, immersive sound experience, enhanced by 11mm speaker drivers delivering rich, full-bodied audio. With up to 11 hours of listening time on a single charge, or up to 31 hours with the charging case, they're ideal for long days and extended listening. The Pixel Buds Pro also support transparency mode, allowing you to stay aware of your surroundings, and adaptive sound adjusts the volume based on the noise level around you. The earbuds are IPX4 water-resistant, making them suitable for workouts or rainy days, and come with multipoint connectivity, letting you seamlessly switch between devices. Google Assistant integration provides hands-free help, and touch controls make it easy to control music, calls, and volume.`,
    },
    {
        id:22,
        product: "huawei buds 4i",
        price: 70,
        image: [
            "https://www.creatuscomputer.com/image/cache/catalog/2022/04/huawei_freebuds_4i_plata_01_l-500x500.png.webp",
            "https://smartbd.com/wp-content/uploads/2023/05/huawei-freebuds-4i.jpg",
            "https://cdn.moglix.com/p/YMoYHAnY0pxPl-xxlarge.jpg",
            "https://images-cdn.ubuy.co.in/66051bcacbd86b08974c3e30-huawei-freebuds-4i-wireless-in-ear.jpg"
        ],
        stock: 14,
        color:["#F8F8F8", "#101010"],
        brand: "huawei",
        category: "earphone",
        featureItem: false,
        review: 4.5,
        description: `The Huawei FreeBuds 4i typically come in three stylish color options: Ceramic White, Carbon Black, and Red, making them versatile for various style preferences. These true wireless earbuds are designed with an ergonomic oval shape for comfortable wear and feature active noise cancellation to minimize surrounding sounds, offering an immersive listening experience. With a long-lasting 10-hour battery life on a single charge and up to 22 hours when using the charging case, they are ideal for extended use throughout the day. The FreeBuds 4i also support touch controls, allowing users to manage music, calls, and noise-canceling settings with ease. Equipped with a 10mm dynamic driver, they deliver rich bass and clear audio quality for a well-rounded listening experience. Additionally, their Bluetooth 5.2 compatibility ensures stable connectivity with minimal lag, enhancing their usability across various devices.`,
    },
    {
        id:23,
        product: "Redmi Buds 3 Pro",
        price: 41,
        image: [
            "https://images-cdn.ubuy.co.in/636cfb31e6f5fd063c77b048-xiaomi-redmi-buds-3-pro-wireless-in-ear.jpg",
            "https://t-tech.com.bd/wp-content/uploads/2024/03/0560495_xiaomi-redmi-buds-3-pro-wireless-in-ear-headphones-bluetooth-wireless-noise-reduction-blackgrey-1200x1347.jpeg",
            "https://images.othoba.com/images/thumbs/0560498_xiaomi-redmi-buds-3-pro-wireless-in-ear-headphones-bluetooth-wireless-noise-reduction-blackgrey.jpeg",
            "https://vibegaming.com.bd/wp-content/uploads/2024/04/Untitled-design-2-29.png"
        ],
        stock: 59,
        color:["#000000", "#ffffff"],
        brand: "Xiaomi",
        category: "earphone",
        featureItem: false,
        review: 4,
        description: `The Redmi Buds 3 Pro are available in two colors: Black and White. These earphones offer an advanced set of features, including Active Noise Cancellation (ANC) that helps to reduce ambient noise, providing an immersive listening experience. They are equipped with a 9mm dynamic driver for high-quality sound and are designed for comfort with an ergonomic fit. The Redmi Buds 3 Pro also feature dual microphones for clearer calls, and they support touch controls for easy access to music and calls. Additionally, they offer IPX4 water resistance, making them suitable for workouts and outdoor activities. The earbuds support Bluetooth 5.2, ensuring a stable connection, and the battery life lasts up to 28 hours with the charging case, while the earbuds themselves provide up to 6 hours of playback on a single charge. The case also supports fast charging via USB-C, adding convenience for users on the go.`,
    },
    {
        id:24,
        product: "Samsung 43CU7700 4k",
        price: 350,
        image: [
            "https://electrabd.com/public/uploads/all/3aaXQ.png",
            "https://storage.googleapis.com/pickaboo-prod/media/catalog/product/cache/90e3b9f4120fc209bf60003e3b0e1323/s/a/samsung-50cu7700-5.jpg",
            "https://www.startech.com.bd/image/cache/catalog/television/samsung/43cu7700/43cu7700-02-500x500.webp",
            "https://a-static.mlcdn.com.br/800x600/smart-tv-43-uhd-4k-led-samsung-43cu7700-wi-fi-bluetooth-alexa-3-hdmi/magazineluiza/237016000/233f8018521a20206839a1e2cb69fe61.jpg"
        ],
        stock: 5,
        color:["#000000"],
        brand: "Samsung",
        category: "tv",
        featureItem: true,
        review: 4,
        description: `he Samsung 43CU7700 4K UHD Smart TV typically comes in one primary color: Black. This TV features a 43-inch display with 4K resolution, offering vibrant visuals with HDR support for better color contrast. It is powered by the Crystal Processor 4K, which enhances picture quality and provides immersive audio through its Dolby Digital Plus system. The TV runs on Tizen OS, providing access to a wide range of streaming apps and services, along with smart features like voice control and home automation compatibility. It also supports multiple connectivity options, including HDMI and USB ports, allowing for easy integration with other devices. The sleek design of the 43CU7700 makes it a stylish addition to any living room or entertainment setup.`,
    },
    {
        id:25,
        product: "apple tv 2",
        price: 200,
        image: [
            "https://static1.pocketnowimages.com/wordpress/wp-content/uploads/2022/10/LI-Apple-TV-4K-3rd-generation-2022.jpg",
            "https://www.gadgetstyler.com/wp-content/uploads/2023/03/apple-tv-4k-hdr-32gb-2021-2nd-gen-mxgy2lla-11665833723.jpg",
            "https://guide-images.cdn.ifixit.com/igi/ge1LZXKrXOHCboiX.medium",
            "https://vibegaming.com.bd/wp-content/uploads/2023/03/Apple-TV-4K-2nd-Gen-5-768x768-1.jpg"
        ],
        stock: 1,
        color:["#000000"],
        brand: "apple",
        category: "tv",
        featureItem: true,
        review: 4.5,
        description: `The Apple TV 2 (2nd generation) typically comes in a single color: black. It features a compact, rectangular design that fits easily into most home entertainment setups. Released in 2010, it supports high-definition video up to 720p, offering a streamlined experience for streaming media from iTunes, Netflix, and other services. It is powered by an Apple A4 chip and has 8 GB of flash storage for syncing content, though it relies heavily on streaming rather than local storage. The device connects to your TV through HDMI, supports Dolby Digital 5.1 surround sound, and includes a simple Apple Remote for navigation. The Apple TV 2 also integrates with iOS devices for seamless media sharing and remote control functionality.`,
    },
    {
        id:26,
        product: "xiaomi tv a pro 43",
        price: 480,
        image: [
            "https://storage.googleapis.com/pickaboo-prod/media/catalog/product/cache/90e3b9f4120fc209bf60003e3b0e1323/x/i/xiaomi-tv-a-pro-43-inch-3.jpg",
            "https://images.tokopedia.net/img/cache/700/VqbcmM/2024/6/20/1582b813-42cf-496b-8d25-cfc2e74190cc.jpg",
            "https://www.radioshack.com.mx/store/medias/100150727.jpg-1200ftw?context=bWFzdGVyfHJvb3R8NTEwNzk3fGltYWdlL2pwZWd8YUdRMEwyaGxPUzg1TVRVMk16azROakV5TlRFd0x6RXdNREUxTURjeU55NXFjR2RmTVRJd01HWjBkd3xjYmNjMDRjY2Q1YjRjMjg0MDM1Mzk0MDRlY2JmYmQyZTMyM2RlYzlmNDExYzY1MWM3NWQ1YWU5YjUzOGE2MTUw",
            "https://www.gadgetpilipinas.net/wp-content/uploads/2024/08/Xiaomi-TV-A-Pro-43-inch-Review-24-768x1024.jpg"
        ],
        stock:5,
        color:["#000000"],
        brand: "Xiaomi",
        category: "tv",
        featureItem: true,
        review: 4.8,
        description: `The Xiaomi TV A Pro 43 is available in multiple color options, typically featuring a sleek black design for a modern and minimalist look. This TV offers a 43-inch 4K Ultra HD display with a slim bezel, providing a large screen experience for vivid and sharp images. It features Android TV with Google Assistant, giving users access to a wide range of apps and services through Google Play Store. The TV is equipped with a quad-core processor, 1GB of RAM, and 8GB of internal storage, ensuring smooth performance and quick access to your favorite content. It also supports Dolby Audio for an immersive sound experience and has built-in Chromecast for easy streaming from other devices. Connectivity options include HDMI, USB, Bluetooth, and Wi-Fi, making it compatible with various external devices. With a variety of smart features and a sleek design, the Xiaomi TV A Pro 43 is designed to deliver a high-quality viewing experience.`,
    },
    {
        id:27,
        product: "huawei vision s",
        price: 470,
        image: [
            "https://consumer.huawei.com/content/dam/huawei-cbg-site/common/mkt/pdp/visions/s/img/pc/huawei-vision-s-stunning-colour.jpg",
            "https://d61s2hjse0ytn.cloudfront.net/product-image/1142/HUAWEI_Vision_S__1.webp",
            "https://d61s2hjse0ytn.cloudfront.net/product-image/1142/HUAWEI_Vision_S_3.webp",
            "https://www.trustedreviews.com/wp-content/uploads/sites/54/2021/07/Huawei-Vision-S-remote-1024x683.jpg"
        ],
        stock: 5,
        color:["#000000","#FFFFFF"],
        brand: "huawei",
        category: "tv",
        featureItem: false,
        review: 4,
        description: `The Huawei Vision S is available in a sleek and modern design with two primary color options: black and white. It features a 4K UHD display with a wide color gamut, ensuring crisp, vibrant visuals. This TV is equipped with HarmonyOS, providing seamless integration with other Huawei devices. The screen has an ultra-thin bezel, maximizing the viewing area, and it supports HDR10+, Dolby Vision, and a 120Hz refresh rate for smooth motion. The Vision S also offers a unique AI camera that can adjust the picture and sound quality based on the viewing environment. It includes high-quality speakers for immersive sound, and smart features such as voice control and remote collaboration functions. The TV connects easily to various devices via multiple HDMI and USB ports, providing versatile connectivity. Its design and functionality make it a great choice for tech enthusiasts seeking a premium smart TV experience.`,
    },
    {
        id:28,
        product: "lg oled evo c3",
        price: 2100,
        image: [
            "https://www.lg.com/content/dam/channel/wcms/cl/images/televisores/oled48c3psa_awh_escl_cl_c/gallery/TV-OLED-42-C3-A-Basic.jpg",
            "https://i.pcmag.com/imagery/reviews/02YsQLGV6dwiW7097fDktgf-2.fit_lim.size_1050x.jpg",
            "https://ledshop.pk/wp-content/uploads/2023/11/c3-6.jpeg",
            "https://cdn3.evostore.io/productimages/fusion/l/fus_810298e.jpg"
        ],
        stock: 5,
        color:["#000000", "#F9F9F9", "#D9E8E2", "#F1C6A8", "#8A2E5C", "#E5332A", "#1E2A78"],
        brand: "lg",
        category: "tv",
        featureItem: false,
        review: 5,
        description: `The LG OLED evo C3 offers a vast range of colors, typically covering 100% of the DCI-P3 color gamut, which allows for incredibly rich and accurate colors. The TV is designed with the latest OLED technology, delivering perfect blacks, vibrant colors, and high contrast ratios. It features an Alpha 9 AI Processor Gen6, enhancing the picture and sound quality by analyzing the content in real time. The display is equipped with an advanced OLED panel, providing excellent brightness levels for an OLED TV, while maintaining deep blacks and sharp contrast. The C3 supports 4K resolution with HDMI 2.1 for smooth gaming experiences, and it includes features such as Dolby Vision IQ, HDR10, and Dolby Atmos for superior video and audio performance. With webOS, users have access to a wide range of apps and smart features, including voice control and seamless integration with other smart home devices. The sleek design, with minimal bezels, ensures that the focus remains on the stunning display, making it an ideal choice for both entertainment and aesthetic appeal in any modern living room.`,
    },
    {
        id:29,
        product: "MacBook Air M2",
        price: 1000,
        image: [
            "https://www.ryans.com/storage/products/main/apple-macbook-air-2022-apple-m2-chip-8gb-ram-21708839214.webp",
            "https://adminapi.applegadgetsbd.com/storage/media/large/MacBook-Air-M2-Midnight-8137.jpg",
            "https://thumbor.arvutitark.ee/oH5gzUhIcunFf0T2yhe2TrtRNsM=/trim/fit-in/800x800/filters:format(webp)/https%3A%2F%2Fstatic.arvutitark.ee%2Fpublic%2Fmedia-hub-olev%2F2022%2F09%2F203664%2Ffd0e1aae-0519-4785-866b-38dd1460706.jpg",
            "https://i0.wp.com/sixcolors.com/wp-content/uploads/2022/06/m2-air-magsafe-6c.png?ssl=1",
        ],
        stock: 2,
        color:["#1D1D1F","#F0E3D1","#B5B9BB"],
        brand: "apple",
        category: "laptop",
        featureItem: true,
        review: 5,
        description: `The MacBook Air M2 is available in four different colors: Midnight, Starlight, Space Gray, and Silver. It features a sleek, thin design with a 13.6-inch Retina display that offers vibrant colors and sharp detail, making it perfect for both work and entertainment. Powered by the Apple M2 chip, it delivers exceptional performance and energy efficiency, allowing for smooth multitasking, app usage, and even demanding tasks like video editing. The laptop has up to 24GB of unified memory and up to 2TB of SSD storage, providing ample space for your files and seamless performance. It also includes a 1080p FaceTime HD camera, improved speakers, and a longer battery life of up to 18 hours, making it an ideal choice for professionals, students, and everyday users. The MacBook Air M2 offers fast charging capabilities and a MagSafe charging port for convenience, while also featuring the latest Wi-Fi 6 technology for faster internet speeds.`,
    },
    {
        id:30,
        product: "google chromebook",
        price: 320,
        image: [
             "https://m.media-amazon.com/images/I/81sDDc7rKqL.jpg",
            "https://i5.walmartimages.com/seo/Pre-Owned-Google-Pixelbook-i7-COA-512GB-SSD-16GB-RAM-Touchscreen-Chromebook-Fair_776a1bf6-6713-4aae-9467-36ad623c8e20.169c3bbb870a9e2e69847d8883254a3b.jpeg",
            "https://images.frandroid.com/wp-content/uploads/2015/03/unnamed-1.png",
            "https://cp24.pl/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/1/_/1_35_88.jpg",
           
        ],
        stock: 2,
        color:["#4285F4", "#DB4437", "#F4B400", "#0F9D58"],
        brand: "google",
        category: "laptop",
        featureItem: true,
        review: 3.5,
        description: `Google Chromebooks are typically available in a range of colors, depending on the model and manufacturer. The standard options usually include shades such as silver, black, white, and sometimes more vibrant colors like coral, blue, or even custom designs. However, the color availability varies from one Chromebook model to another. The Chromebook itself runs on Chrome OS, offering a streamlined, web-based operating system designed for simplicity and speed. Chromebooks are generally lightweight, portable, and come with various screen sizes, typically ranging from 11 to 15 inches. They are known for their quick boot times, long battery life, and seamless integration with Google services like Google Drive, Gmail, and Google Docs. Many models feature Intel or ARM processors, up to 8GB of RAM, and storage options typically around 32GB to 128GB, often relying on cloud storage. The display quality can vary, but Full HD (1080p) is common for many models. Connectivity includes Wi-Fi, Bluetooth, and sometimes LTE support for on-the-go usage.`,
    },
    

];



export default ProductData;